<?php

return [
    'base_url' => env('INAPROC_REKAP_BASE_URL', 'https://data.inaproc.id/'),
    'node_binary' => env('INAPROC_REKAP_NODE_BINARY', PHP_OS_FAMILY === 'Windows' && file_exists('C:\\Program Files\\nodejs\\node.exe') ? 'C:\\Program Files\\nodejs\\node.exe' : 'node'),
    'runner_path' => env('INAPROC_REKAP_RUNNER_PATH', 'scripts/scrape-inaproc-rekap-nasional.js'),
    'timeout_seconds' => (int) env('INAPROC_REKAP_TIMEOUT', 90),
    'wait_until_text' => env('INAPROC_REKAP_WAIT_TEXT', 'Realisasi Swakelola'),
    'sleep_seconds' => (int) env('INAPROC_REKAP_SLEEP_SECONDS', 3),

    'provinces' => [
        ['code' => 'D1', 'name' => 'ACEH', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D1&view=Nilai'],
        ['code' => 'D25', 'name' => 'BALI', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D25&view=Nilai'],
        ['code' => 'D35', 'name' => 'BANGKA BELITUNG', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D35&view=Nilai'],
        ['code' => 'D43', 'name' => 'BANTEN', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D43&view=Nilai'],
        ['code' => 'D52', 'name' => 'BENGKULU', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D52&view=Nilai'],
        ['code' => 'D63', 'name' => 'DI YOGYAKARTA', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D63&view=Nilai'],
        ['code' => 'D69', 'name' => 'DKI JAKARTA', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D69&view=Nilai'],
        ['code' => 'D76', 'name' => 'GORONTALO', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D76&view=Nilai'],
        ['code' => 'D83', 'name' => 'JAMBI', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D83&view=Nilai'],
        ['code' => 'D95', 'name' => 'JAWA BARAT', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D95&view=Nilai'],
        ['code' => 'D122', 'name' => 'JAWA TENGAH', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D122&view=Nilai'],
        ['code' => 'D158', 'name' => 'JAWA TIMUR', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D158&view=Nilai'],
        ['code' => 'D197', 'name' => 'KALIMANTAN BARAT', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D197&view=Nilai'],
        ['code' => 'D212', 'name' => 'KALIMANTAN SELATAN', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D212&view=Nilai'],
        ['code' => 'D226', 'name' => 'KALIMANTAN TENGAH', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D226&view=Nilai'],
        ['code' => 'D241', 'name' => 'KALIMANTAN TIMUR', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D241&view=Nilai'],
        ['code' => 'D533', 'name' => 'KALIMANTAN UTARA', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D533&view=Nilai'],
        ['code' => 'D256', 'name' => 'KEPULAUAN RIAU', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D256&view=Nilai'],
        ['code' => 'D264', 'name' => 'LAMPUNG', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D264&view=Nilai'],
        ['code' => 'D279', 'name' => 'MALUKU', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D279&view=Nilai'],
        ['code' => 'D291', 'name' => 'MALUKU UTARA', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D291&view=Nilai'],
        ['code' => 'D301', 'name' => 'NUSA TENGGARA BARAT', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D301&view=Nilai'],
        ['code' => 'D312', 'name' => 'NUSA TENGGARA TIMUR', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D312&view=Nilai'],
        ['code' => 'D334', 'name' => 'PAPUA', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D334&view=Nilai'],
        ['code' => 'D364', 'name' => 'PAPUA BARAT', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D364&view=Nilai'],
        ['code' => 'D1004', 'name' => 'PAPUA BARAT DAYA', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D1004&view=Nilai'],
        ['code' => 'D1005', 'name' => 'PAPUA PEGUNUNGAN', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D1005&view=Nilai'],
        ['code' => 'D1003', 'name' => 'PAPUA SELATAN', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D1003&view=Nilai'],
        ['code' => 'D1002', 'name' => 'PAPUA TENGAH', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D1002&view=Nilai'],
        ['code' => 'D376', 'name' => 'RIAU', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D376&view=Nilai'],
        ['code' => 'D389', 'name' => 'SULAWESI BARAT', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D389&view=Nilai'],
        ['code' => 'D395', 'name' => 'SULAWESI SELATAN', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D395&view=Nilai'],
        ['code' => 'D421', 'name' => 'SULAWESI TENGAH', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D421&view=Nilai'],
        ['code' => 'D433', 'name' => 'SULAWESI TENGGARA', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D433&view=Nilai'],
        ['code' => 'D446', 'name' => 'SULAWESI UTARA', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D446&view=Nilai'],
        ['code' => 'D462', 'name' => 'SUMATERA BARAT', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D462&view=Nilai'],
        ['code' => 'D482', 'name' => 'SUMATERA SELATAN', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D482&view=Nilai'],
        ['code' => 'D498', 'name' => 'SUMATERA UTARA', 'url' => 'https://data.inaproc.id/profil-pengadaan?tahun=2026&jenis=3&instansi=D498&view=Nilai'],
    ],
];
